# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import agent_pb2 as agent__pb2


class llmStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.stream = channel.unary_stream(
                '/llm/stream',
                request_serializer=agent__pb2.TextRequest.SerializeToString,
                response_deserializer=agent__pb2.TextResponse.FromString,
                )


class llmServicer(object):
    """Missing associated documentation comment in .proto file."""

    def stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_llmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'stream': grpc.unary_stream_rpc_method_handler(
                    servicer.stream,
                    request_deserializer=agent__pb2.TextRequest.FromString,
                    response_serializer=agent__pb2.TextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class llm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/llm/stream',
            agent__pb2.TextRequest.SerializeToString,
            agent__pb2.TextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class embedingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.embed_documents = channel.unary_unary(
                '/embeding/embed_documents',
                request_serializer=agent__pb2.Docs.SerializeToString,
                response_deserializer=agent__pb2.FloatListList.FromString,
                )
        self.embed_query = channel.unary_unary(
                '/embeding/embed_query',
                request_serializer=agent__pb2.Query.SerializeToString,
                response_deserializer=agent__pb2.FloatList.FromString,
                )


class embedingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def embed_documents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def embed_query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_embedingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'embed_documents': grpc.unary_unary_rpc_method_handler(
                    servicer.embed_documents,
                    request_deserializer=agent__pb2.Docs.FromString,
                    response_serializer=agent__pb2.FloatListList.SerializeToString,
            ),
            'embed_query': grpc.unary_unary_rpc_method_handler(
                    servicer.embed_query,
                    request_deserializer=agent__pb2.Query.FromString,
                    response_serializer=agent__pb2.FloatList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embeding', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class embeding(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def embed_documents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embeding/embed_documents',
            agent__pb2.Docs.SerializeToString,
            agent__pb2.FloatListList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def embed_query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embeding/embed_query',
            agent__pb2.Query.SerializeToString,
            agent__pb2.FloatList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class compressed_promptStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.compress = channel.unary_unary(
                '/compressed_prompt/compress',
                request_serializer=agent__pb2.Compress.SerializeToString,
                response_deserializer=agent__pb2.Result.FromString,
                )


class compressed_promptServicer(object):
    """Missing associated documentation comment in .proto file."""

    def compress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_compressed_promptServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'compress': grpc.unary_unary_rpc_method_handler(
                    servicer.compress,
                    request_deserializer=agent__pb2.Compress.FromString,
                    response_serializer=agent__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'compressed_prompt', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class compressed_prompt(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def compress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compressed_prompt/compress',
            agent__pb2.Compress.SerializeToString,
            agent__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
