# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\" \n\x0eMessageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x17\n\x08TokenNum\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x17\n\x06Tokens\x12\r\n\x05token\x18\x01 \x03(\t\"X\n\x0bTextRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x14\n\x0cmodel_kwargs\x18\x02 \x01(\t\x12\x17\n\x0fpipeline_kwargs\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x1e\n\x0cTextResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\")\n\rFloatListList\x12\x18\n\x04\x64ocs\x18\x01 \x03(\x0b\x32\n.FloatList\"\x1a\n\tFloatList\x12\r\n\x05query\x18\x01 \x03(\x02\")\n\x05Query\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nquery_inst\x18\x02 \x01(\t\"(\n\x04\x44ocs\x12\x0c\n\x04\x64ocs\x18\x01 \x03(\t\x12\x12\n\nembed_inst\x18\x02 \x01(\t\"W\n\x06Result\x12\x0c\n\x04\x64ocs\x18\x01 \x01(\t\x12\x15\n\rorigin_tokens\x18\x02 \x01(\x05\x12\x19\n\x11\x63ompressed_tokens\x18\x03 \x01(\x05\x12\r\n\x05ratio\x18\x04 \x01(\t\"?\n\x08\x43ompress\x12\x0c\n\x04\x64ocs\x18\x01 \x03(\t\x12\x13\n\x0binstruction\x18\x02 \x01(\t\x12\x10\n\x08question\x18\x03 \x01(\t2\xa0\x01\n\x03llm\x12\'\n\x06stream\x12\x0c.TextRequest\x1a\r.TextResponse0\x01\x12:\n\x1cget_num_tokens_from_messages\x12\x0f.MessageRequest\x1a\t.TokenNum\x12\x34\n\x18get_tokens_from_messages\x12\x0f.MessageRequest\x1a\x07.Tokens2W\n\x08\x65mbeding\x12(\n\x0f\x65mbed_documents\x12\x05.Docs\x1a\x0e.FloatListList\x12!\n\x0b\x65mbed_query\x12\x06.Query\x1a\n.FloatList23\n\x11\x63ompressed_prompt\x12\x1e\n\x08\x63ompress\x12\t.Compress\x1a\x07.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=15
  _globals['_MESSAGEREQUEST']._serialized_end=47
  _globals['_TOKENNUM']._serialized_start=49
  _globals['_TOKENNUM']._serialized_end=72
  _globals['_TOKENS']._serialized_start=74
  _globals['_TOKENS']._serialized_end=97
  _globals['_TEXTREQUEST']._serialized_start=99
  _globals['_TEXTREQUEST']._serialized_end=187
  _globals['_TEXTRESPONSE']._serialized_start=189
  _globals['_TEXTRESPONSE']._serialized_end=219
  _globals['_FLOATLISTLIST']._serialized_start=221
  _globals['_FLOATLISTLIST']._serialized_end=262
  _globals['_FLOATLIST']._serialized_start=264
  _globals['_FLOATLIST']._serialized_end=290
  _globals['_QUERY']._serialized_start=292
  _globals['_QUERY']._serialized_end=333
  _globals['_DOCS']._serialized_start=335
  _globals['_DOCS']._serialized_end=375
  _globals['_RESULT']._serialized_start=377
  _globals['_RESULT']._serialized_end=464
  _globals['_COMPRESS']._serialized_start=466
  _globals['_COMPRESS']._serialized_end=529
  _globals['_LLM']._serialized_start=532
  _globals['_LLM']._serialized_end=692
  _globals['_EMBEDING']._serialized_start=694
  _globals['_EMBEDING']._serialized_end=781
  _globals['_COMPRESSED_PROMPT']._serialized_start=783
  _globals['_COMPRESSED_PROMPT']._serialized_end=834
# @@protoc_insertion_point(module_scope)
