# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\"X\n\x0bTextRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x14\n\x0cmodel_kwargs\x18\x02 \x01(\t\x12\x17\n\x0fpipeline_kwargs\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x1e\n\x0cTextResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\")\n\rFloatListList\x12\x18\n\x04\x64ocs\x18\x01 \x03(\x0b\x32\n.FloatList\"\x1a\n\tFloatList\x12\r\n\x05query\x18\x01 \x03(\x02\")\n\x05Query\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nquery_inst\x18\x02 \x01(\t\"(\n\x04\x44ocs\x12\x0c\n\x04\x64ocs\x18\x01 \x03(\t\x12\x12\n\nembed_inst\x18\x02 \x01(\t\"W\n\x06Result\x12\x0c\n\x04\x64ocs\x18\x01 \x01(\t\x12\x15\n\rorigin_tokens\x18\x02 \x01(\x05\x12\x19\n\x11\x63ompressed_tokens\x18\x03 \x01(\x05\x12\r\n\x05ratio\x18\x04 \x01(\t\"?\n\x08\x43ompress\x12\x0c\n\x04\x64ocs\x18\x01 \x03(\t\x12\x13\n\x0binstruction\x18\x02 \x01(\t\x12\x10\n\x08question\x18\x03 \x01(\t2.\n\x03llm\x12\'\n\x06stream\x12\x0c.TextRequest\x1a\r.TextResponse0\x01\x32W\n\x08\x65mbeding\x12(\n\x0f\x65mbed_documents\x12\x05.Docs\x1a\x0e.FloatListList\x12!\n\x0b\x65mbed_query\x12\x06.Query\x1a\n.FloatList23\n\x11\x63ompressed_prompt\x12\x1e\n\x08\x63ompress\x12\t.Compress\x1a\x07.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEXTREQUEST']._serialized_start=15
  _globals['_TEXTREQUEST']._serialized_end=103
  _globals['_TEXTRESPONSE']._serialized_start=105
  _globals['_TEXTRESPONSE']._serialized_end=135
  _globals['_FLOATLISTLIST']._serialized_start=137
  _globals['_FLOATLISTLIST']._serialized_end=178
  _globals['_FLOATLIST']._serialized_start=180
  _globals['_FLOATLIST']._serialized_end=206
  _globals['_QUERY']._serialized_start=208
  _globals['_QUERY']._serialized_end=249
  _globals['_DOCS']._serialized_start=251
  _globals['_DOCS']._serialized_end=291
  _globals['_RESULT']._serialized_start=293
  _globals['_RESULT']._serialized_end=380
  _globals['_COMPRESS']._serialized_start=382
  _globals['_COMPRESS']._serialized_end=445
  _globals['_LLM']._serialized_start=447
  _globals['_LLM']._serialized_end=493
  _globals['_EMBEDING']._serialized_start=495
  _globals['_EMBEDING']._serialized_end=582
  _globals['_COMPRESSED_PROMPT']._serialized_start=584
  _globals['_COMPRESSED_PROMPT']._serialized_end=635
# @@protoc_insertion_point(module_scope)
